config/routes.rb
Deck::Application.routes.draw do

  devise_for :members

  devise_for :members do
   get 'members', :to => 'home#members', :as => :member_root # Rails 3
  end
  
  match '/invoice' => 'home#invoice', :as => :invoice
  match '/printout' => 'home#printout', :as => :printout

  match '/ping' => 'home#ping', :as => :invoice

  match '/members' => 'home#members', :as => :members

  root :to => "home#index"

end

app/models/invoice.rb
class Invoice
  
  attr_accessor :invoicee
  attr_accessor :invoicer
  
  def date
    Time.now.strftime("01.%m.%Y")
  end
  
  def taxless
    if Location.utilized_workspaces == 0
      return 0
    end
    (Invoice.total_costs / Location.utilized_workspaces).round(2)
  end
  
  def vat
    (self.taxless * Invoice.vat).round(2)
  end
  
  def total
    (self.taxless + self.vat).round(2)
  end
  
  def self.total_costs
    ENV['TOTAL_RENT'].to_f + ENV['TOTAL_SERVICES'].to_f
  end
  
  def self.vat
    ENV['VAT'].to_f
  end
  
end

app/models/location.rb
module Location
  
  def self.workspace_capacity
    ENV['CAPACITY'].to_i
  end
  
  def self.free_workspaces
    self.workspace_capacity - self.utilized_workspaces
  end
  
  def self.utilized_workspaces
    Member.all.count
  end
  
  def self.street_address
    ENV['STREET_ADDRESS']
  end

  def self.postcode
    ENV['POSTCODE']
  end

  def self.city
    ENV['CITY']
  end
  
  def self.lat
    ENV['LAT'].to_f
  end
  
  def self.lon
    ENV['LON'].to_f
  end
  
  def self.rent_for_potential_new_member
    (Invoice.total_costs / (Location.utilized_workspaces + 1)).round(2)
  end
  
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :company, :y_code, :linkedin, :twitter, :phone, :url
  # attr_accessible :title, :body

  attr_accessor :invite_code
  attr_accessible :invite_code

  attr_accessible :tables, :stealth
  
  validates_each :invite_code, :on => :create do |record, attr, value|
      record.errors.add attr, "Please enter correct invite code" unless
        value && value == ENV['INVITE_CODE']
  end
    
  def name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @members = Member.all.reject {|x| x.stealth? }
    render :layout => 'public'
  end
  
  def invoice
    @invoice = Invoice.new
    @invoice.invoicer = Member.find(ENV['INVOICER_ID'])
    @invoice.invoicee = current_member
    # render :layout => 'invoice'
  end

  def printout
    @members = Member.all
    render :layout => nil
  end
  
  def ping
    render :text => 'a-ok'
  end
  
  def members
    authenticate_member!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def random_rotation_css
    rotate = -16 + rand(32)
    margin_top = -30 + rand(60)
    margin_left = -40 + rand(80)
<<-END
transform: rotate(#{rotate}deg);
-ms-transform: rotate(#{rotate}deg); /* IE 9 */
-webkit-transform: rotate(#{rotate}deg); /* Safari and Chrome */
top: #{margin_top}px;
left: #{margin_left}px;
END
  end

  def slight_random_rotation_css
    rotate = -10 + rand(20)
    margin_top = -10 + rand(20)
    margin_left = -20 + rand(40)
<<-END
transform: rotate(#{rotate}deg);
-ms-transform: rotate(#{rotate}deg); /* IE 9 */
-webkit-transform: rotate(#{rotate}deg); /* Safari and Chrome */
END
  end

  def sideways_random_rotation_css
    rotate = -110 + rand(20)
    margin_top = -10 + rand(20)
    margin_left = -20 + rand(40)
<<-END
transform: rotate(#{rotate}deg);
-ms-transform: rotate(#{rotate}deg); /* IE 9 */
-webkit-transform: rotate(#{rotate}deg); /* Safari and Chrome */
END
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="stack orderable">
  <div class="card card-backside card-site-title" style="<%= sideways_random_rotation_css %>"></div>
</div>

<div class="stack orderable">

  <div id="card-facilities" class="card card-about shufflable unselectable" style="<%= slight_random_rotation_css %>">
    <h2 class="about-heading" style="margin-top: 85px;">Facilities</h2>
    <ul>
      <li>12 personal desk spaces</li>
      <li>sofa corner</li>
      <li>kitchen</li>
      <li>meeting/workshop area</li>
      <li>enough windows yet no direct sunlight</li>
      <li>easy access to street</li>
      <li>135 m<sup>2</sup> total area</li>
    </ul>
  </div>

  <div id="card-services" class="card card-about shufflable unselectable" style="<%= slight_random_rotation_css %>">
    <h2 class="about-heading" style="margin-top: 130px;">Services</h2>
    <ul>
      <li>200 MB internet by Welho</li>
      <li>Burglar alarm featuring security guards by Securitas</li>
      <li>Printer</li>
      <li>Weekly cleaning</li>
    </ul>
  </div>

  <div id="card-location" class="card card-about shufflable unselectable" style="<%= slight_random_rotation_css %>">
    <h2 class="about-heading">Location</h2>
    <p>
      Deck is located in the hip and happening Punavuori district. 
    </p>  
    <p>
      There's plenty of lunch options nearby, not to mention the Alepa store right in the opposite building.
    </p>
    <p>
      The final stop of tram line 1A to Eira is right outside our doorstep. Bus 14 rides very close as well.
    </p>
  </div>

  <div id="card-about" class="card card-about shufflable unselectable" style="<%= slight_random_rotation_css %>">
    <h2 class="about-heading">About</h2>
    <p>
      Deck is a co-working space (in French "ty&ouml;huone") for those who work with software and internet. 
    </p>
    <p>
      Our aim is to sustain a synergistic and fun working community for freelancers.
    </p>
    <p>
      We are located at Pursimiehenkatu 26 H in Punavuori, Helsinki.
    </p>
    <!-- <span class="read-more">&raquo; click &raquo;</span> -->
  </div>

</div>

<div class="stack orderable">

  <% @members.shuffle.each do |member| %>
  <div class="card member-card unselectable shufflable" style="background: url(<%= image_path "member-#{member.first_name && member.first_name.downcase}.jpg" %>); <%= random_rotation_css %>">
      <div class="member-name">
        <%= member.name %>
      </div>
      <div class="member-company">  
        <%= member.company %>
      </div>
      
        <div class="some">
          <% if member.linkedin && !member.linkedin.blank? %>
            <a href="<%= member.linkedin %>" target="_blank">
              <img src="http://www.linkedin.com/img/webpromo/btn_liprofile_blue_80x15.png" width="80" height="15" border="0" alt="View Pirkka Esko's profile on LinkedIn" class="grayscale linkedin-some">
            </a>
          <% end %>
          <% if member.twitter && !member.twitter.blank? %>
            <a href="https://twitter.com/<%= member.twitter %>" class="twitter-follow-button grayscale twitter-some" data-show-count="false" data-show-screen-name="true">Follow @<%= member.twitter%></a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>    
          <% end %>
          <% if member.url && !member.url.blank? %>
            <%= link_to "visit&nbsp;website".html_safe, member.url, :class => 'www-some', :target => '_blank' %>
          <% end %>
        </div>
      </div>
  <% end %>

</div>

<div class="stack orderable">

  <% [1,2,3,4,5,7].shuffle.each do |photo| %>
  <div id="card-photo-<%= photo %>" class="card stack-card unselectable shufflable" style="<%= random_rotation_css %>">
    <div class="photo" style="background: url(<%= image_path "photo#{photo}.png" %>);"></div>
  </div>
  <% end %>

</div>

<div class="stack orderable">
  <div id="map-card" class="card card-map" style="<%= slight_random_rotation_css %>">
    <div id="map"></div>
  </div>
</div>

<div class="stack orderable">
  <div class="card card-about" style="<%= slight_random_rotation_css %>">

  <h2 class="relevant-heading">Relevant to your interests?</h2>

  <p>
    <%= Location.free_workspaces %> out of <%= Location.workspace_capacity %> work spaces are currently available for rent. 
    
  </p>
  <p>
    Monthly rent for single work space is approximately <%= Location.rent_for_potential_new_member.to_i %> € (+VAT).
  </p> 
  
  <p>
    For enquiries, please contact Pirkka&nbsp;Esko.
  </p>
  <p>mail@pirkkaesko.com <br/> +358 50 3062243</p>

  </div>
</div>

<script type="text/javascript">
$(function () {
  
  // stamen layer
  var layer = new L.StamenTileLayer("toner-lite");
  var map = new L.Map("map", {
      center: new L.LatLng(<%= Location.lat%>, <%= Location.lon %>),
      zoom: 12, /* or 17 or 12 */
      scrollWheelZoom: false,
      touchZoom: false
  });
  map.addLayer(layer);
  
  // // control for centering
  // 
  // var MyControl = L.Control.extend({
  //     options: {
  //         position: 'bottomleft'
  //     },
  // 
  //     onAdd: function (map) {
  //         // create the control container with a particular class name
  //         var container = L.DomUtil.create('div', 'center-map-control');
  // 
  //         // ... initialize other DOM elements, add listeners, etc.
  //         
  //         $('.center-map-control').click(function () {
  //           console.log('centering...');
  //           map.panTo(new L.LatLng(60.15827, 24.934));
  //         });
  // 
  //         return container;
  //     }
  // });
  // 
  // map.addControl(new MyControl());
  // 
  
  // experiment
  x = function () {
    map.panTo(new L.LatLng(60.15827, 24.934));
  }
  
  var deckIcon = L.icon({
    iconUrl: '/assets/deck-marker.png',
    iconSize:     [80, 47],
    iconAnchor:   [40, 0],
    popupAnchor:  [-3, -76]
  });  
  
  // add a marker in the given location, attach some popup content to it and open the popup
  L.marker([<%= Location.lat%>, <%= Location.lon %>], {icon: deckIcon}).addTo(map);

  // gravity for the map panning

  map.on('mousedown', function(e) {
    console.log('mousedown');
    sinceMoved = 0;
  });

  map.on('mouseup', function(e) {
    console.log('mouseup');
    sinceMoved = 0;
  });

  map.on('mouseout', function(e) {
    console.log('mouseout');
    sinceMoved = 0;
  });

  map.on('mousein', function(e) {
    console.log('mousein');
    sinceMoved = 0;
  });

  map.on('mousemove', function(e) {
    console.log('mousemove');
    sinceMoved = 0;
  });
  
  var sinceMoved = 0;
  
  var timer = setInterval(function(){
    // console.log('sincemoved: ' + sinceMoved);
    sinceMoved += 1;
    if (sinceMoved > 10) {
      map.panTo(new L.LatLng(60.15827, 24.934));
      sinceMoved = 0;
    }
  },500);
  
});
</script>

<div class="clickability-notification">
  The cards are clickable. ^__^
</div>

app/views/home/invoice.html.erb
<h1>Vuokralasku</h1>

<ul class="thumbnails">
    <li class="span4" class="thumbnail">
      
      <strong>Laskun vastaanottaja</strong><br />
      <%= @invoice.invoicee.company %><br />
      <%= @invoice.invoicee.name %><br />
      <%= Location.street_address %><br />
      <%= Location.postcode %> <%= Location.city %><br />
      Y-tunnus: <%= @invoice.invoicee.y_code %><br />

    </li>


    <li class="span4" class="thumbnail">
      
      <strong>Laskun lähettäjä</strong><br />

        <%= @invoice.invoicer.company %><br />
        <%= @invoice.invoicer.name %><br />
        <%= Location.street_address %><br />
        <%= Location.postcode %> <%= Location.city %><br />
        Y-tunnus: <%= @invoice.invoicer.y_code %><br />
    </li>
</ul>



<table class="table table-bordered">
  <tr>
    <td>Päivämäärä</td>
    <td><%= @invoice.date %></td>
  </tr>
  <tr>
    <td>Selite</td>
    <td>Työpisteen vuokra osoitteessa <%= Location.street_address %>, <%= Location.postcode %> <%= Location.city %>.
    </td>
  </tr>
  <tr>
    <td>Veroton</td>
    <td><%= @invoice.taxless %> €</td>
  </tr>
  <tr>
    <td>ALV <%= (Invoice.vat*100).to_i %>%</td>
    <td><%= @invoice.vat%> €</td>
  </tr>
  <tr>
    <td>Maksettava</td>
    <td><%= @invoice.total %> €</td>
  </tr>
  <tr>
    <td>Maksuehto</td>
    <td>3 pv netto</td>
  </tr>
  <tr>
    <td>Saajan IBAN-tilinumero</td>
    <td><%= ENV['IBAN'] %></td>
  </tr>
  <tr>
    <td>SWIFT/BIC</td>
    <td><%= ENV['SWIFT'] %></td>
  </tr>
</table>

app/views/home/members.html.erb
<h1>Member Home</h1>

<p>
Welcome to the DECK member area. 
</p>

<h2>List of members</h2>

<table>
  <tr>
    <th>Name </th>
    <th>Email </th>
    <th>Phone </th>
    <th>Id#</th>
    <th>Other</th>
  </tr>
<% Member.all(:order => :last_name).each do |m| %>
  <tr>
    <td>
      <%= m.name%>
    </td>
    <td>
      <%= m.email%>
    </td>
    <td>
      <%= m.phone%>
    </td>
    <td>
      <%= m.id %>
    </td>
    <td>
      <%= m.stealth && 'stealthmode' %>
    </td>
  </tr>
<% end %>
</table>

app/views/home/printout.html.erb
<% @members.each do |m| %>

<p>
  <%= m.name %><br/>
  <%= m.company %><br/>
</p>
  
<% end %>

app/views/layouts/_analytics.html.erb
  
<% if ENV["GA_CODE"] %>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= ENV["GA_CODE"] %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<% end %>

app/views/layouts/_font.html.erb
<!--
/* @license
 * MyFonts Webfont Build ID 2563745, 2013-05-24T04:02:54-0400
 * 
 * The fonts listed in this notice are subject to the End User License
 * Agreement(s) entered into by the website owner. All other parties are 
 * explicitly restricted from using the Licensed Webfonts(s).
 * 
 * You may obtain a valid license at the URLs below.
 * 
 * Webfont: Gibson by Canada Type
 * URL: http://www.myfonts.com/fonts/canadatype/gibson/regular/
 * Copyright: Copyright &#x00A9; 2011 Rod McDonald. Published by Canada Type. All rights
 * reserved.
 * 
 * 
 * License: http://www.myfonts.com/viewlicense?type=web&buildid=2563745
 * 
 * © 2013 MyFonts Inc
*/

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!-- leaflet -->
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.css" />
  <!--[if lte IE 8]>
      <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.ie.css" />
  <![endif]-->
  <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
  <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.2.1"></script>  
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="container">
      <div class="member-content">
        
        <% if notice %>
        <p class="alert"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert"><%= alert %></p>
        <% end %>
        
        <ul class="member-area-menu">
        <li><%= link_to 'Public website', '/' %></li>
        <li><%= link_to 'Member home', '/members' %></li>
        <% if current_member %>
          <li><%= link_to 'Edit details', edit_member_registration_path %></li>
          <li><%= link_to 'Invoice', invoice_path, :target => "_blank" %></li>
          <li><%= link_to 'Sign out', destroy_member_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_member_session_path %></li>
        <% end %>
        </ul>
        <div style="clear: both;"></div>

      <%= yield %>
  
      </div>
  

    </div>

    <%= render :partial => 'layouts/analytics'%>

</body>
</html>

app/views/layouts/invoice.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vuokralasku</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <!-- leaflet -->
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.css" />
  <!--[if lte IE 8]>
      <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.ie.css" />
  <![endif]-->
  <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="container">
    
    <% if notice %>
    <p class="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>


    <%= yield %>



  </div>

  <%= render :partial => 'layouts/analytics'%>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>  
  <title>Deck</title>

  <meta property="og:title" content="Deck - Workspace for Software Pros">
  <meta property="og:image" content="http://deck.fi/assets/deck-share.png">
  <meta property="og:site_name" content="Deck">
  <meta property="og:description" content="Deck is a co-working space for freelancers who work with software and internet, located at Pursimiehenkatu 26 H in Punavuori, Helsinki.">
  <meta property="og:url" content="http://deck.fi/">
  <meta property="og:type" content="website">

  <meta name="viewport" content="width=device-height">

  <%= render :partial => 'layouts/font' %>  
  
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!-- leaflet -->
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.css" />
  <!--[if lte IE 8]>
      <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.ie.css" />
  <![endif]-->
  <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
  <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.2.1"></script>  
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="container stack-container">
    
      <% if notice %>
      <p class="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert"><%= alert %></p>
      <% end %>


      <%= yield %>
  
    </div>

    <%= render :partial => 'layouts/analytics'%>
    
</body>
</html>